const memberList = [
    { "name": "Khoa Nguyễn",
      "type": "Project Leader",
      "desc": "Người dẫn dắt và quản lí dự án, lên kế hoạch cũng như phụ trách kĩ thuật...",
      "img": "/team/khoa.jpeg",
      "link": "https://www.facebook.com/yun.khngn",
    },
    { "name": "Đức Cường",
      "type": "Truyền thông",
      "desc": "Quản lí fanpage, làm truyền thông và cập nhật thông tin về dự án...",
      "img": "/team/cuong.jpg",
      "link": "https://www.facebook.com/harrypham.04",
    },
    { "name": "Phan Thảo",
      "type": "Truyền thông",
      "desc": "Quản lí fanpage, làm truyền thông và cập nhật thông tin về dự án...",
      "img": "/team/thao.jpg",
      "link": "https://www.facebook.com/pthaor0110",
    },
    { "name": "Tuấn Anh",
      "type": "Media/Photo",
      "desc": "Chụp ảnh, quay video, media...",
      "img": "/team/tuanbro.jpg",
      "link": "https://www.facebook.com/meditQuynh69",
    },
    { "name": "Hoàng Sơn",
      "type": "Content",
      "desc": "Tổng hợp các dự án, viết content...",
      "img": "/team/son.jpg",
      "link": "https://www.facebook.com/SownLee1105",
    },
    { "name": "Hồng Hiếu",
      "type": "Content",
      "desc": "Tổng hợp các dự án, viết content....",
      "img": "/team/hieu.jpg",
      "link": "https://www.facebook.com/hty.hieu.2",
    },
    { "name": "Lê Hoàng",
      "type": "Hậu cần",
      "desc": "Hỗ trợ nhân sự, hậu cần...",
      "img": "/team/hoang.jpg",
      "link": "https://www.facebook.com/profile.php?id=100028218953844",
    },
]

export default memberList;