export {default as Homepage} from './Homepage'
export {default as About} from './About'
export {default as Pics} from './Pics'
export {default as Poster} from './Poster'
export {default as Mail} from './Mail'
export {default as Prj} from './Prj'